export const NO_ADDRESS = "NO_ADDRESS";
export const ADD_ADDRESS = "ADD_ADDRESS";
export const EDIT_ADDRESS = "EDIT_ADDRESS";
export const COMPLETE_PAYMENT = "COMPLETE_PAYMENT";

export const ORDER_PENDING = "ORDER_PENDING";
export const ORDER_SUCCESS = "ORDER_SUCCESS";
export const ORDER_ERROR = "ORDER_ERROR";